services:
  localstack:
    image: localstack/localstack:3.7.1
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack:/var/lib/localstack"
      #- "/var/run/docker.sock:/var/run/docker.sock"
